//! winit `KeyCode` → [`VKey`] 转换表。显式逐变体匹配，不依赖 Debug 名字符串
//! （winit 用 `BracketLeft`/`Backquote`，[`VKey`] 用 `LeftBracket`/`Grave`）。
//! 鼠标键（`MouseLeft` 等）不是 KeyCode，由鼠标事件单独喂给 KeyMap。

use mcv_game::keymap::VKey;
use winit::keyboard::KeyCode;

/// 数字键 1..9 → 快捷栏槽位 0..8（MC 中是 9 个独立键位，本引擎键位表
/// 单动作单键容不下，先保持硬编码直绑）。
pub fn hotbar_slot(code: KeyCode) -> Option<usize> {
    let slot = match code {
        KeyCode::Digit1 => 0,
        KeyCode::Digit2 => 1,
        KeyCode::Digit3 => 2,
        KeyCode::Digit4 => 3,
        KeyCode::Digit5 => 4,
        KeyCode::Digit6 => 5,
        KeyCode::Digit7 => 6,
        KeyCode::Digit8 => 7,
        KeyCode::Digit9 => 8,
        _ => return None,
    };
    Some(slot)
}

pub fn vkey_of(code: KeyCode) -> Option<VKey> {
    let vk = match code {
        KeyCode::KeyA => VKey::KeyA,
        KeyCode::KeyB => VKey::KeyB,
        KeyCode::KeyC => VKey::KeyC,
        KeyCode::KeyD => VKey::KeyD,
        KeyCode::KeyE => VKey::KeyE,
        KeyCode::KeyF => VKey::KeyF,
        KeyCode::KeyG => VKey::KeyG,
        KeyCode::KeyH => VKey::KeyH,
        KeyCode::KeyI => VKey::KeyI,
        KeyCode::KeyJ => VKey::KeyJ,
        KeyCode::KeyK => VKey::KeyK,
        KeyCode::KeyL => VKey::KeyL,
        KeyCode::KeyM => VKey::KeyM,
        KeyCode::KeyN => VKey::KeyN,
        KeyCode::KeyO => VKey::KeyO,
        KeyCode::KeyP => VKey::KeyP,
        KeyCode::KeyQ => VKey::KeyQ,
        KeyCode::KeyR => VKey::KeyR,
        KeyCode::KeyS => VKey::KeyS,
        KeyCode::KeyT => VKey::KeyT,
        KeyCode::KeyU => VKey::KeyU,
        KeyCode::KeyV => VKey::KeyV,
        KeyCode::KeyW => VKey::KeyW,
        KeyCode::KeyX => VKey::KeyX,
        KeyCode::KeyY => VKey::KeyY,
        KeyCode::KeyZ => VKey::KeyZ,
        KeyCode::Digit0 => VKey::Digit0,
        KeyCode::Digit1 => VKey::Digit1,
        KeyCode::Digit2 => VKey::Digit2,
        KeyCode::Digit3 => VKey::Digit3,
        KeyCode::Digit4 => VKey::Digit4,
        KeyCode::Digit5 => VKey::Digit5,
        KeyCode::Digit6 => VKey::Digit6,
        KeyCode::Digit7 => VKey::Digit7,
        KeyCode::Digit8 => VKey::Digit8,
        KeyCode::Digit9 => VKey::Digit9,
        KeyCode::F1 => VKey::F1,
        KeyCode::F2 => VKey::F2,
        KeyCode::F3 => VKey::F3,
        KeyCode::F4 => VKey::F4,
        KeyCode::F5 => VKey::F5,
        KeyCode::F6 => VKey::F6,
        KeyCode::F7 => VKey::F7,
        KeyCode::F8 => VKey::F8,
        KeyCode::F9 => VKey::F9,
        KeyCode::F10 => VKey::F10,
        KeyCode::F11 => VKey::F11,
        KeyCode::F12 => VKey::F12,
        KeyCode::Space => VKey::Space,
        KeyCode::Comma => VKey::Comma,
        KeyCode::Period => VKey::Period,
        KeyCode::Slash => VKey::Slash,
        KeyCode::Semicolon => VKey::Semicolon,
        KeyCode::Quote => VKey::Apostrophe,
        KeyCode::Minus => VKey::Minus,
        KeyCode::Equal => VKey::Equal,
        KeyCode::BracketLeft => VKey::LeftBracket,
        KeyCode::BracketRight => VKey::RightBracket,
        KeyCode::Backslash => VKey::Backslash,
        KeyCode::Backquote => VKey::Grave,
        KeyCode::Enter => VKey::Enter,
        KeyCode::Backspace => VKey::Backspace,
        KeyCode::Tab => VKey::Tab,
        KeyCode::Escape => VKey::Escape,
        KeyCode::Insert => VKey::Insert,
        KeyCode::Delete => VKey::Delete,
        KeyCode::Home => VKey::Home,
        KeyCode::End => VKey::End,
        KeyCode::PageUp => VKey::PageUp,
        KeyCode::PageDown => VKey::PageDown,
        KeyCode::ArrowLeft => VKey::ArrowLeft,
        KeyCode::ArrowUp => VKey::ArrowUp,
        KeyCode::ArrowRight => VKey::ArrowRight,
        KeyCode::ArrowDown => VKey::ArrowDown,
        KeyCode::ShiftLeft => VKey::ShiftLeft,
        KeyCode::ShiftRight => VKey::ShiftRight,
        KeyCode::ControlLeft => VKey::ControlLeft,
        KeyCode::ControlRight => VKey::ControlRight,
        KeyCode::AltLeft => VKey::AltLeft,
        KeyCode::AltRight => VKey::AltRight,
        _ => return None,
    };
    Some(vk)
}
