#!/usr/bin/env python3
# DEVELOP_ONLY 数据管道（同 assets/ 素材政策）：
#   从 Mojang 官方语言文件（data/lang/en_us.json / zh_cn.json，版权归 Mojang，
#   发布前删除或替换为自维护表）挑出引擎 UI 实际用到的 key 子集，
#   生成 compact 表（data/lang/compact/），运行时只嵌 compact 不嵌全量。
#
# 用法（仓库根目录）:  python3 ci/gen-lang.py
#
# 产物:
#   data/lang/compact/en.json / zh.json  —— 只含用到的 key，人工审阅用
#   data/lang/compact/table.rs           —— i18n.rs include! 的编译期静态表
#     [(key, en, zh), ...]，引擎无 JSON 运行时依赖，故直接生成 Rust 源码。
#
# 官方语言文件中不存在的 key 走 data/lang/extra.json（自维护中英对照）。
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LANG_DIR = ROOT / "game/mcv_app/data/lang"
OUT_DIR = LANG_DIR / "compact"

# 引擎 UI 实际用到的官方 key（对照 app.rs 菜单文案）。
# 注释为 app.rs 中对应的界面文案。
UI_KEYS = [
    "menu.singleplayer",          # 主菜单：单人游戏
    "menu.quit",                  # 主菜单：退出
    "options.title",              # 设置标题（"Options"/"选项"，无省略号）
    "selectWorld.create",         # 世界列表：创建新世界
    "gui.back",                   # 各处：返回
    "selectWorld.newWorld",       # 新建世界标题
    "selectWorld.gameMode",       # 游戏模式
    "gameMode.survival",
    "gameMode.creative",
    "gameMode.hardcore",
    "options.renderDistance",     # 渲染距离
    "options.sensitivity",        # 灵敏度
    "menu.paused",                # 游戏暂停
    "menu.returnToGame",          # 回到游戏
    "menu.returnToMenu",          # 保存并退出（到标题屏）
    "menu.options",               # 主菜单/暂停：设置
    "options.language",           # 设置：语言
    "options.on",                 # 开关：开
    "options.off",                # 开关：关
    "options.renderClouds",       # 设置：渲染云（Options.java cloudStatus）
    "options.clouds.fast",        # 云：流畅
    "options.clouds.fancy",       # 云：高品质
    "deathScreen.title",          # 死亡界面标题
    "deathScreen.respawn",        # 死亡界面：重生
    "deathScreen.titleScreen",    # 死亡界面：回标题屏
]

# extra.json 中实际用到的自维护 key
EXTRA_KEYS = [
    "mcv.selectWorld.title",            # 选择世界
    "mcv.createWorld.create",           # 创建世界
    "mcv.mode.survival",                # 生存（短标签，官方只有"生存模式"）
    "mcv.mode.creative",                # 创造
    "mcv.mode.hardcore",                # 极限
    "mcv.createWorld.mode",             # 模式：%s
    "mcv.createWorld.hardcoreDesc",     # 同生存，死亡即删除世界
    "mcv.options.renderDistanceChunk",  # 渲染距离：%s 区块
    "mcv.options.sensitivityScale",     # 灵敏度：%sx
    "mcv.createWorld.survivalDesc",     # 生存模式说明
    "mcv.createWorld.creativeDesc",     # 创造模式说明
    "mcv.options.languageTitle",        # 语言（无省略号短标签）
    "mcv.death.hardcoreInfo",           # 极限模式：世界将被删除提示
]


def main() -> int:
    en_full = json.loads((LANG_DIR / "en_us.json").read_text(encoding="utf-8"))
    zh_full = json.loads((LANG_DIR / "zh_cn.json").read_text(encoding="utf-8"))
    extra = {
        k: v
        for k, v in json.loads((LANG_DIR / "extra.json").read_text(encoding="utf-8")).items()
        if not k.startswith("_")
    }

    entries = {}  # key -> (en, zh)
    missing = []
    for key in UI_KEYS:
        if key not in en_full or key not in zh_full:
            missing.append(key)
            continue
        entries[key] = (en_full[key], zh_full[key])
    for key in EXTRA_KEYS:
        if key in en_full or key in zh_full:
            sys.exit(f"extra key {key!r} 与官方语言文件冲突，请改从官方取")
        if key not in extra:
            missing.append(key)
            continue
        entries[key] = (extra[key]["en"], extra[key]["zh"])
    if missing:
        sys.exit(f"缺 key: {missing}")
    if len(entries) > 40:
        sys.exit(f"key 数 {len(entries)} 超过 40 上限")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "en.json").write_text(
        json.dumps({k: v[0] for k, v in entries.items()}, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
    )
    (OUT_DIR / "zh.json").write_text(
        json.dumps({k: v[1] for k, v in entries.items()}, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
    )

    rows = ",\n".join(
        f'    ({rust_str(k)}, {rust_str(v[0])}, {rust_str(v[1])})' for k, v in entries.items()
    )
    table = (
        "// @generated by ci/gen-lang.py —— 请勿手改，改 key 后重跑脚本\n"
        "// DEVELOP_ONLY: en 列取自 Mojang 官方 en_us.json（版权同材质包政策，\n"
        "// 发布前删除或替换为自维护表）；mcv. 前缀 key 来自 data/lang/extra.json。\n"
        "pub const TABLE: [(&str, &str, &str); "
        f"{len(entries)}] = [\n{rows},\n];\n"
    )
    (OUT_DIR / "table.rs").write_text(table, encoding="utf-8")

    total = sum(len(p.read_bytes()) for p in OUT_DIR.iterdir())
    print(f"{len(entries)} keys -> {OUT_DIR} (共 {total} B)")
    return 0


def rust_str(s: str) -> str:
    # JSON 串与 Rust 字符串字面量转义兼容（语言文件里主要是 \" \\ %s \n）
    return json.dumps(s, ensure_ascii=False)


if __name__ == "__main__":
    sys.exit(main())
